version: "3.8"
services:
  api-disney-alkemy:
    build: .
    depends_on:
     - bdd-mysql
    ports:
     - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=bdd-mysql
      - DB_DIALECT=mysql
      - DATABASE=disney_world
      - DB_USER=root
      - DB_PASSWORD=root
      - TOKEN_CRYPT=secret
      - SENDGRID_KEY=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
      - SENDGRID_EMAIL=blasdelgado10@gmail.com
    links:
      - bdd-mysql
    container_name: api-disney-alkemy
  bdd-mysql:
    image: mysql:8.0
    restart: always
    ports: 
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=blas
      - MYSQL_PASSWORD=password 
    container_name: mysql-bdd
    volumes:
      - ./database/disney2.sql:/docker-entrypoint-initdb.d/disney2.sql
volumes:
  dumps:
